name: quizzers
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.3
  freezed: ^2.4.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  retrofit: ^4.0.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  retrofit_generator: ^8.0.6
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - .env
